import pandas as pd
import matplotlib.pyplot as plt
import os

def plot_training_metrics(log_dir="./training_logs", output_dir="outputs"):
    """
    Reads the progress.csv file generated by Stable-Baselines3 and plots 
    important tracking metrics like the reward and loss values.
    """
    csv_path = os.path.join(log_dir, "progress.csv")
    if not os.path.exists(csv_path):
        print(f"Error: {csv_path} not found. Please run `python main.py --mode train` first to generate data.")
        return
        
    os.makedirs(output_dir, exist_ok=True)
    try:
        df = pd.read_csv(csv_path)
    except pd.errors.ParserError:
        # Handle cases where training was restarted and headers were appended mid-file
        df = pd.read_csv(csv_path, on_bad_lines='skip')
    
    # The standard keys saved by PPO algorithm in SB3
    metrics_to_plot = {
        'Total Loss': ['train/loss'],
        'Policy and Value Loss': ['train/policy_gradient_loss', 'train/value_loss'],
        'Average Episodic Reward': ['rollout/ep_rew_mean']
    }
    
    for title, keys in metrics_to_plot.items():
        plt.figure(figsize=(10, 6))
        plotted = False
        
        for key in keys:
            if key in df.columns:
                # Drop NaN rows specifically for this line segment
                valid_data = df[['time/total_timesteps', key]].dropna()
                if not valid_data.empty:
                    plt.plot(valid_data['time/total_timesteps'], valid_data[key], label=key, linewidth=2)
                    plotted = True
        
        if plotted:
            plt.title(f"PPO Training Progress: {title}")
            plt.xlabel("Total Timesteps")
            plt.ylabel("Value")
            plt.legend()
            plt.grid(True, linestyle='--', alpha=0.7)
            
            safe_title = title.replace('/', '_').replace(' ', '_').lower()
            out_file = os.path.join(output_dir, f"training_{safe_title}.png")
            plt.savefig(out_file)
            print(f"Successfully generated metric plot: {out_file}")
            
        plt.close()

    # Plot custom advanced metrics
    custom_csv = os.path.join(log_dir, "training_metrics.csv")
    if os.path.exists(custom_csv):
        try:
            df_custom = pd.read_csv(custom_csv)
        except pd.errors.ParserError:
            df_custom = pd.read_csv(custom_csv, on_bad_lines='skip')
        if not df_custom.empty:
            # Calculate PDR
            df_custom['pdr'] = (df_custom['total_delivered'] / (df_custom['total_delivered'] + df_custom['total_dropped'])) * 100.0
            df_custom['pdr'] = df_custom['pdr'].fillna(0)
            
            plt.figure(figsize=(10, 6))
            plt.plot(df_custom['step'], df_custom['pdr'], color='green', linewidth=2)
            plt.title("Packet Delivery Ratio over Training")
            plt.xlabel("Timesteps")
            plt.ylabel("PDR (%)")
            plt.grid(True, linestyle='--', alpha=0.7)
            plt.savefig(os.path.join(output_dir, "training_custom_pdr.png"))
            plt.close()
            
            # Stacked Reward Breakdowns
            plt.figure(figsize=(10, 6))
            rewards = ['ep_reward_delivery', 'ep_reward_qos', 'ep_reward_progress']
            penalties = ['ep_penalty_loops', 'ep_penalty_congestion']
            
            # Add urgency if present in the data
            if 'ep_reward_urgency' in df_custom.columns:
                rewards.append('ep_reward_urgency')
            
            # Smooth the data for stackplots
            window = max(1, len(df_custom) // 50)
            rwds_smoothed = [df_custom[col].rolling(window, min_periods=1).mean() for col in rewards if col in df_custom.columns]
            pens_smoothed = [df_custom[col].rolling(window, min_periods=1).mean() for col in penalties if col in df_custom.columns]
            
            reward_labels = [col for col in rewards if col in df_custom.columns]
            penalty_labels = [col for col in penalties if col in df_custom.columns]
            
            if rwds_smoothed:
                plt.stackplot(df_custom['step'], rwds_smoothed, labels=reward_labels, alpha=0.7)
            if pens_smoothed:
                plt.stackplot(df_custom['step'], pens_smoothed, labels=penalty_labels, alpha=0.5)
            
            plt.axhline(0, color='black', linewidth=1)
            plt.title("Reward & Penalty Components over Training")
            plt.xlabel("Timesteps")
            plt.ylabel("Cumulative Reward Contribution")
            plt.legend(loc='upper left')
            plt.savefig(os.path.join(output_dir, "training_custom_rewards_components.png"))
            plt.close()
            print("Successfully generated custom advanced metric plots: PDR and Reward Breakdown.")

if __name__ == "__main__":
    # Ensure current working directory spans the project root when executed directly
    project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    log_directory = os.path.join(project_root, "training_logs")
    output_directory = os.path.join(project_root, "outputs")
    
    plot_training_metrics(log_dir=log_directory, output_dir=output_directory)
